# Generated by Django 3.1.4 on 2021-01-27 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_MultiVendor', '0002_auto_20210128_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
